branches:
  except:
    - ben-branch
    - codeReview
    - create-job
    - master
    - r-backend
    - r-branch
    - signup-backend
    - ui-design
branches:
  only:
    - travis-branch
script: build.sh
